[package]
name = "SQL"
version = "0.1.0"
authors = ["Gabe <finkegabriel@gmail.com>"]
edition = "2018"


[dependencies]
clap = "2.32.0"
postgres = "0.17.3"
cargo-script = "0.2.8"
barrel = "0.6.5"
cpython = "0.5.0"